### ISSUE TITLE
Elo jędruś

### ISSUE THREAD

**Issue by Caidler** [projektkck2016/smieciarka#1]
Daj mi lajka

**Comment by projektkck2016** [comment]
i co dalej?

**Comment by projektkck2016** [comment]
co to za gówno
jprd.....

**Comment by Caidler** [comment]
Nie wiem kurwa xD trzeba stworzyć plik

**Comment by projektkck2016** [comment]
jaki plik?!

**Comment by projektkck2016** [comment]
co my mamy zrobić
bożeeeeeeeeee

**Comment by Caidler** [comment]
Stworzyć plik musimy i wrzucać do niego zmiany

**Comment by Caidler** [comment]
w Code spróbuj coś stworzyć i daj mi jakieś prawa abym mógł w to ingerować i commitować

**Comment by projektkck2016** [comment]
jesteś wolny Daidler!
jesteś wolnym człowiekiem! Daje Ci prawa ludzkie i boże!
